version: '3.8'

services:
  db-postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-simple:/var/lib/postgresql/data
#    networks:
#      - app-network
    env_file:
      - ./api-service/.env.development.local

  cassandra:
    image: cassandra:4.0.5
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    volumes:
      - ./volumes/cassandra:/var/lib/cassandra
#     https://medium.com/featurepreneur/enabling-sasi-index-86604c37d31b
#     file cassandra.yaml in docker copy out here
#     https://stackoverflow.com/questions/48734670/sasi-index-in-cassandra-and-how-it-differs-from-normal-indexing
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
#    networks:
#      - db_cassandra_network

  nginx:
    image: nginx:alpine
    container_name: reverse_server
    hostname: reverse_server
    ports:
      - "80:80"
      - "433:433"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - asset-service
#    networks:
#      - asset-network

  asset-service:
    build:
      context: asset-service
      dockerfile: Dockerfile
    container_name: asset-service
    hostname: asset-service
#    Uncomment to expose to connect direct by port 8080 of server
    ports:
      - "8080:8080"
    volumes:
      - "./asset-service/public:/app/public"
#    networks:
#      - asset-network

  redis:
    image: redis:alpine3.16
    container_name: redis
    ports:
      - "6379:6379"

#  api-service:
#    build:
#      context: api-service
#      dockerfile: Dockerfile
#    container_name: api-service
#    hostname: api-service
#    #    Uncomment to expose to connect direct by port 8080 of server
#    #    ports:
#    #      - "4001:4001"
#    networks:
#      - api-network
#
#  chat-service:
#    build:
#      context: chat-service
#      dockerfile: Dockerfile
#    container_name: chat-service
#    hostname: chat-service
#    #    Uncomment to expose to connect direct by port 8080 of server
#    #    ports:
#    #      - "4001:4001"
#    networks:
#      - chat-network
#
  # Version 1
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.3.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9997:9997"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9000:8080"
    restart: always
    depends_on:
      - broker
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=127.0.0.1:9092

#networks:
##  db_cassandra_network:
#  app-network:
#    driver: bridge

#networks:
#  api-network:
#    driver: bridge
#  chat-network:
#    driver: bridge
#  asset-network:
#    driver: bridge