version: '3.8'

services:
  db-postgres:
    image: postgres:14.5-alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres-simple:/var/lib/postgresql/data
    #    networks:
    #      - app-network
    env_file:
      - ./api-service/.env

  cassandra:
    image: cassandra:4.0.5
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    volumes:
      - ./volumes/cassandra:/var/lib/cassandra
      #     https://medium.com/featurepreneur/enabling-sasi-index-86604c37d31b
      #     file cassandra.yaml in docker copy out here
      #     https://stackoverflow.com/questions/48734670/sasi-index-in-cassandra-and-how-it-differs-from-normal-indexing
      - ./cassandra.yaml:/etc/cassandra/cassandra.yaml
  #    networks:
  #      - db_cassandra_network

  asset-service:
    build:
      context: asset-service
      dockerfile: Dockerfile
    container_name: asset-service
    hostname: asset-service
    #    Uncomment to expose to connect direct by port 8080 of server
    ports:
      - "8080:8080"
    volumes:
      - "./asset-service/public:/app/public"

#  api-service:
#    build:
#      context: api-service
#      dockerfile: Dockerfile
#    container_name: api-service
#    hostname: api-service
#    #    Uncomment to expose to connect direct by port 8080 of server
#    #    ports:
#    #      - "4001:4001"
#
#  chat-service:
#    build:
#      context: chat-service
#      dockerfile: Dockerfile
#    container_name: chat-service
#    hostname: chat-service
#    #    Uncomment to expose to connect direct by port 8080 of server
#    #    ports:
#    #      - "4001:4001"
